[skin.modelos]
tablero=conf/skin_default/Tablero.3ds
jugador_1=conf/skin_default/Pinguino.3ds
jugador_2=conf/skin_default/Robot.3ds
barrera_1=conf/skin_default/Barrera_Pinguino.3ds
barrera_2=conf/skin_default/Barrera_Robot.3ds
celda=conf/skin_default/Celda.3ds

[skin.texturas]
tablero=conf/skin_default/Moss0138_10_S.jpg
antorcha=conf/skin_default/fire.bmp
celda=conf/skin_default/Moss0138_2_S.jpg
terreno=conf/skin_default/piso3_TX.jpg
skydome=conf/skin_default/3.tree.skydome.png

[gui]
gui_cfg=conf/gui_default/guiskin.cfg
creditos=conf/gui_default/creditos1.jpg

[gui.fonts]
default=conf/gui_default/defaultfont2.png
menu_button=conf/gui_default/bigfont.png
tooltip=conf/gui_default/tooltipfont.png
buttons=conf/gui_default/botonFont.png
window=conf/gui_default/windowfont.png

[gui.botones]
vuelta_1=conf/gui_default/boton4_2-1_vuelta.png
vuelta_1_2=conf/gui_default/boton4_2-1_vuelta-2.png #presionado

vuelta_2=conf/gui_default/boton4_2-2_vuelta.png
vuelta_2_2=conf/gui_default/boton4_2-2_vuelta-2.png #presionado

vuelta_3=conf/gui_default/boton5_2-2_vuelta.png
vuelta_3_2=conf/gui_default/boton5_2-2_vuelta-2.png #presionado

frente=conf/gui_default/boton5_2-1_frente.png
frente_2=conf/gui_default/boton5_2-1_frente-2.png #presionado

pausa_1=conf/gui_default/boton1_2_pausa.png
pausa_1_2=conf/gui_default/boton1_2_pausa-2.png #presionado

pausa_2=conf/gui_default/boton2_2_pausa.png
pausa_2_2=conf/gui_default/boton2_2_pausa-2.png #presionado

menu=conf/gui_default/boton3_2_menu.png
menu_2=conf/gui_default/boton3_2_menu-2.png #presionado

mover_pin=conf/gui_default/mover_pingu.png
mover_pin_2=conf/gui_default/mover_pingu_2.png #presionado

mover_rob=conf/gui_default/mover_robot.png
mover_rob_2=conf/gui_default/mover_robot_2.png #presionado

set_Barr_pin=conf/gui_default/poner_pingu.png
set_Barr_pin_2=conf/gui_default/poner_pingu_2.png #presionado

set_Barr_rob=conf/gui_default/poner_robot.png
set_Barr_rob_2=conf/gui_default/poner_robot_2.png #presionado

gir_est_Barr_pin=conf/gui_default/girar_1_pingu.png
gir_est_Barr_pin_2=conf/gui_default/girar_1_pingu_2.png #presionado

gir_est_Barr_rob=conf/gui_default/girar_1_robot.png
gir_est_Barr_rob_2=conf/gui_default/girar_1_robot_2.png #presionado

gir_nort_Barr_pin=conf/gui_default/girar_2_pingu.png
gir_nort_Barr_pin_2=conf/gui_default/girar_2_pingu_2.png #presionado

gir_nort_Barr_rob=conf/gui_default/girar_2_robot.png
gir_nort_Barr_rob_2=conf/gui_default/girar_2_robot_2.png #presionado
