[skin.modelos]
tablero=conf/skin_default/Tablero.obj
jugador_1=conf/skin_default/Mono.obj
jugador_2=conf/skin_default/MonoBlanco.obj
jugador_sombra=conf/skin_default/MonoSombra.obj
antorcha=conf/skin_default/Lumbrera.obj
barrera=conf/skin_default/Barrera.obj
celda=conf/skin_default/Celda.obj

[skin.texturas]
tablero=conf/skin_default/Moss0138_10_S.jpg
antorcha=conf/skin_default/fire.bmp
barrera=conf/skin_default/BrickOldDirty0078_S.jpg
celda=conf/skin_default/Moss0138_2_S.jpg
terreno=conf/skin_default/piso3_TX.jpg
terreno_height=conf/skin_default/piso3_HM.bmp
skydome=conf/skin_default/3.tree.skydome.png

[gui]
gui_cfg=conf/gui_default/guiskin.cfg
creditos=conf/gui_default/creditos1.jpg

[gui.fonts]
default=conf/gui_default/defaultfont2.png
menu_button=conf/gui_default/bigfont.png
tooltip=conf/gui_default/tooltipfont.png
buttons=conf/gui_default/botonFont.png
window=conf/gui_default/windowfont.png

[gui.botones]
vuelta_1=conf/gui_default/boton4_2-1_vuelta.png
vuelta_1_2=conf/gui_default/boton4_2-1_vuelta-2.png #presionado

vuelta_2=conf/gui_default/boton4_2-2_vuelta.png
vuelta_2_2=conf/gui_default/boton4_2-2_vuelta-2.png #presionado

vuelta_3=conf/gui_default/boton5_2-2_vuelta.png
vuelta_3_2=conf/gui_default/boton5_2-2_vuelta-2.png #presionado

frente=conf/gui_default/boton5_2-1_frente.png
frente_2=conf/gui_default/boton5_2-1_frente-2.png #presionado

pausa_1=conf/gui_default/boton1_2_pausa.png
pausa_1_2=conf/gui_default/boton1_2_pausa-2.png #presionado

pausa_2=conf/gui_default/boton2_2_pausa.png
pausa_2_2=conf/gui_default/boton2_2_pausa-2.png #presionado

menu=conf/gui_default/boton3_2_menu.png
menu_2=conf/gui_default/boton3_2_menu-2.png #presionado
